MODEL:
  ATTR:
    CHECKPOINT_PATH: checkpoints/train/RATIO_Train_epoch6_val_loss0.5285_match_acc0.8932_all_acc0.8964_.pth
    MAC_BERT:
      NAME: MAC_BERT
      MODEL_PATH: data/MacBert
      TRUNCATION: true
      PADDING: max_length
      MAX_LENGTH: 8
      LEARNING_RATE: 0.00001
    TEXT_DIM: 768
    IMAGE_DIM: 2048
    NUM_ATTR: 12
  ALL_MATCH:
    CHECKPOINT_PATH: checkpoints/train/ALL_MATCH_Train_epoch8_val_loss0.5973_val_acc0.7897_.pth
    MAC_BERT:
      NAME: MAC_BERT
      MODEL_PATH: data/MacBert
      TRUNCATION: true
      PADDING: max_length
      MAX_LENGTH: 32
      LEARNING_RATE: 0.00001
    TEXT_DIM: 768
    IMAGE_DIM: 2048
    NUM_ATTR: 12

OPTIMIZER:
  LEARNING_RATE: 0.0002
  COEF_LR: 5.0
  WEIGHT_DECAY: 0.00001
  WARMUP_PROPORTION: 0.1
  ETA_MIN: 0.00005

OPTIM:
  LR: 0.0003
  MIN_LR: 0.00001
  WEIGHT_DECAY: 0.005
  WARMUP_STEPS: 3000
  WARMUP_LR: 0.00001
  LR_DECAY_RATE: 0.9


FINETUNE:
  DATA_PATH: ./data/finetune_all_match.txt
  ATTR_PATH: ./data/attr_to_attrvals.json
  OUT_PATH: checkpoints/
  EPOCHS: 30
  RATIO: 0.9
  SHUFFLE: FALSE
  SEED: 2022
  TRAIN_BATCH: 512
  VAL_BATCH: 256
  NUM_WORKERS: 4
  LOG_STEP: 10
  K_FOLD: 9


ATTR_TRAIN:
  DATA_PATH: ./data/all_attr_match.txt
  ATTR_PATH: ./data/attr_to_attrvals.json
  OUT_PATH: checkpoints/
  EPOCHS: 40
  RATIO: 0.95
  SHUFFLE: FALSE
  SEED: 43
  TRAIN_BATCH: 1536
  VAL_BATCH: 768
  NUM_WORKERS: 4
  LOG_STEP: 40

ALL_TRAIN:
  TRAIN_PATH: ./data/train_all_match.txt
  VAL_PATH: ./data/finetune_all_match.txt
  ATTR_PATH: ./data/attr_to_attrvals.json
  OUT_PATH: checkpoints/
  EPOCHS: 40
  RATIO: 0.95
  SHUFFLE: FALSE
  SEED: 43
  TRAIN_BATCH: 512
  VAL_BATCH: 512
  NUM_WORKERS: 4
  LOG_STEP: 40
  


TEST:
  DATA_PATH: ./data/test_attr_A.txt
  ATTR_PATH: ./data/attr_to_attrvals.json
  OUT_PATH: result/all_0.923_attr_0.932.txt
  ATTR_CHECKPOINT_PATH: checkpoints/train/ATTR_Train_epoch14_val_loss0.1704_val_acc0.9322_.pth
  ALL_CHECKPOINT_PATH: checkpoints/finetune/FINETUNE_MATCH_Train_epoch9_val_loss0.1721_val_acc0.9232_.pth