MODEL:
  ATTR:
    CHECKPOINT_PATH: checkpoints/train/RATIO_Train_epoch6_val_loss0.5285_match_acc0.8932_all_acc0.8964_.pth
    MAC_BERT:
      NAME: MAC_BERT
      MODEL_PATH: data/MacBert
      TRUNCATION: true
      PADDING: max_length
      MAX_LENGTH: 8
      LEARNING_RATE: 0.00001
    TEXT_DIM: 768
    IMAGE_DIM: 2048
    NUM_ATTR: 12
  ALL_MATCH:
    CHECKPOINT_PATH: checkpoints/train/CAT_epoch240_val_loss0.4944_val_acc0.8317_.pth
    MAC_BERT:
      NAME: MAC_BERT
      MODEL_PATH: data/MacBert
      TRUNCATION: true
      PADDING: max_length
      MAX_LENGTH: 32
      LEARNING_RATE: 0.00001
    TEXT_DIM: 768
    IMAGE_DIM: 2048
    NUM_ATTR: 12

OPTIMIZER:
  LEARNING_RATE: 0.0001
  COEF_LR: 5.0
  WEIGHT_DECAY: 0.
  WARMUP_PROPORTION: 0.1
  ETA_MIN: 0.00005

OPTIM:
  LR: 0.0001
  MIN_LR: 0.00001
  WEIGHT_DECAY: 0.
  WARMUP_STEPS: 3000
  WARMUP_LR: 0.00001
  LR_DECAY_RATE: 0.9


FINETUNE:
  DATA_PATH: ./data/new_finetune_data.txt
  DATA_PATH_2: ./data/new_fine.txt
  ATTR_PATH: ./data/attr_to_attrvals.json
  OUT_PATH: checkpoints/
  EPOCHS: 14
  RATIO: 0.8
  SHUFFLE: FALSE
  SEED: 2
  TRAIN_BATCH: 128
  VAL_BATCH: 256
  NUM_WORKERS: 4
  LOG_STEP: 10
  K_FOLD: 5


ATTR_TRAIN:
  DATA_PATH: ./data/new_finetune_data.txt
  ATTR_PATH: ./data/attr_dic.json
  OUT_PATH: checkpoints/
  EPOCHS: 40
  RATIO: 0.96
  SHUFFLE: FALSE
  SEED: 2021
  TRAIN_BATCH: 3072
  VAL_BATCH: 1536
  NUM_WORKERS: 4
  LOG_STEP: 40

ALL_TRAIN:
  TRAIN_PATH: './data/equal_processed_data/coarse_pretrain.txt,./data/equal_processed_data/fine_pretrain.txt'
  VAL_PATH: './data/equal_processed_data/fine_val.txt,./data/equal_processed_data/coarse1412.txt'
  ATTR_PATH: ./data/equal_processed_data/attr_to_attrvals.json
  OUT_PATH: checkpoints/
  EPOCHS: 600
  RATIO: 0.95
  SHUFFLE: FALSE
  SEED: 3
  TRAIN_BATCH: 768
  VAL_BATCH: 512
  NUM_WORKERS: 4
  LOG_STEP: 40
  


TEST:
  DATA_PATH: ./data/equal_split_word/test_A.txt
  ATTR_PATH: ./data/attr_to_attrvals.json
  OUT_PATH: result/test_A_match_1.txt
  ATTR_CHECKPOINT_PATH: checkpoints/train/NORM_SE_ATTR_Train_epoch9_val_loss0.1702_val_acc0.9339_.pth
  ALL_CHECKPOINT_PATH: checkpoints/finetune/CAT_76_ADD_CHANGE_2244_FINETUNE_MATCH_Train_epoch6_val_loss0.2086_val_acc0.9195_.pth